<?php

/**
 * This is the model base class for the table "proveedores".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Proveedores".
 *
 * Columns in table "proveedores" available as properties of the model,
 * followed by relations of table "proveedores" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $direccion
 * @property integer $id_ciudad
 * @property string $correo
 * @property string $nombreContacto
 * @property string $apellidoContacto
 * @property string $rutProveedor
 *
 * @property Ciudades $idCiudad
 * @property RegistroFactura[] $registroFacturas
 * @property Vehiculos[] $vehiculoses
 */
abstract class BaseProveedores extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'proveedores';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Proveedor|Proveedores', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('id_ciudad', 'numerical', 'integerOnly'=>true),
			array('nombre, correo, nombreContacto, apellidoContacto, rutProveedor', 'length', 'max'=>30),
			array('direccion', 'length', 'max'=>40),
			array('direccion, id_ciudad, correo, nombreContacto, apellidoContacto, rutProveedor', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, direccion, id_ciudad, correo, nombreContacto, apellidoContacto, rutProveedor', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCiudad' => array(self::BELONGS_TO, 'Ciudades', 'id_ciudad'),
			'registroFacturas' => array(self::HAS_MANY, 'RegistroFactura', 'id_proveedor'),
			'vehiculoses' => array(self::HAS_MANY, 'Vehiculos', 'idProveedor'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'direccion' => Yii::t('app', 'Direccion'),
			'id_ciudad' => null,
			'correo' => Yii::t('app', 'Correo'),
			'nombreContacto' => Yii::t('app', 'Nombre Contacto'),
			'apellidoContacto' => Yii::t('app', 'Apellido Contacto'),
			'rutProveedor' => Yii::t('app', 'Rut Proveedor'),
			'idCiudad' => null,
			'registroFacturas' => null,
			'vehiculoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('direccion', $this->direccion, true);
		$criteria->compare('id_ciudad', $this->id_ciudad);
		$criteria->compare('correo', $this->correo, true);
		$criteria->compare('nombreContacto', $this->nombreContacto, true);
		$criteria->compare('apellidoContacto', $this->apellidoContacto, true);
		$criteria->compare('rutProveedor', $this->rutProveedor, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}