<?php

/**
 * This is the model base class for the table "bitacoras".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bitacoras".
 *
 * Columns in table "bitacoras" available as properties of the model,
 * followed by relations of table "bitacoras" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_vehiculo
 * @property string $fecha
 * @property integer $kilometraje_inicial
 * @property integer $kilometraje_final
 * @property string $litros_adicionales
 *
 * @property Vehiculos $idVehiculo
 */
abstract class BaseBitacoras extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'bitacoras';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Bitacoras|Bitacorases', $n);
	}

	public static function representingColumn() {
		return 'fecha';
	}

	public function rules() {
		return array(
			array('id_vehiculo, fecha, kilometraje_inicial, kilometraje_final, litros_adicionales', 'required'),
			array('id_vehiculo, kilometraje_inicial, kilometraje_final', 'numerical', 'integerOnly'=>true),
			array('litros_adicionales', 'length', 'max'=>10),
			array('id, id_vehiculo, fecha, kilometraje_inicial, kilometraje_final, litros_adicionales', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idVehiculo' => array(self::BELONGS_TO, 'Vehiculos', 'id_vehiculo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_vehiculo' => null,
			'fecha' => Yii::t('app', 'Fecha'),
			'kilometraje_inicial' => Yii::t('app', 'Kilometraje Inicial'),
			'kilometraje_final' => Yii::t('app', 'Kilometraje Final'),
			'litros_adicionales' => Yii::t('app', 'Litros Adicionales'),
			'idVehiculo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_vehiculo', $this->id_vehiculo);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('kilometraje_inicial', $this->kilometraje_inicial);
		$criteria->compare('kilometraje_final', $this->kilometraje_final);
		$criteria->compare('litros_adicionales', $this->litros_adicionales, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}