<?php

/**
 * This is the model base class for the table "modelos_vehiculos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ModelosVehiculos".
 *
 * Columns in table "modelos_vehiculos" available as properties of the model,
 * followed by relations of table "modelos_vehiculos" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 *
 * @property Vehiculos[] $vehiculoses
 */
abstract class BaseModelosVehiculos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'modelos_vehiculos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Modelo|Modelos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>30),
			array('id, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'vehiculoses' => array(self::HAS_MANY, 'Vehiculos', 'idModelo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'vehiculoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}