<?php

/**
 * This is the model base class for the table "areas_empresa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AreasEmpresa".
 *
 * Columns in table "areas_empresa" available as properties of the model,
 * followed by relations of table "areas_empresa" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 *
 * @property CargosEmpresa[] $cargosEmpresas
 */
abstract class BaseAreasEmpresa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'areas_empresa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Area Empresa|Areas Empresa', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>30),
			array('id, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cargosEmpresas' => array(self::HAS_MANY, 'CargosEmpresa', 'id_area_empresa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'cargosEmpresas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}