<?php

/**
 * This is the model base class for the table "orden_trabajo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrdenTrabajo".
 *
 * Columns in table "orden_trabajo" available as properties of the model,
 * followed by relations of table "orden_trabajo" available as properties of the model.
 *
 * @property integer $id
 * @property integer $nro_guia
 * @property integer $id_vehiculo
 * @property integer $id_rf
 * @property string $kilometraje
 * @property string $fecha
 * @property string $creado
 * @property string $modificado
 *
 * @property DetallesOt[] $detallesOts
 * @property Vehiculos $idVehiculo
 * @property RegistroFactura $idregistroFactura
 */
abstract class BaseOrdenTrabajo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'orden_trabajo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrdenTrabajo|OrdenTrabajos', $n);
	}

	public static function representingColumn() {
		return 'nro_guia';
	}

	public function rules() {
		return array(
			array('nro_guia, id_vehiculo, id_rf, fecha, creado, modificado', 'required'),
			array('nro_guia, id_vehiculo, id_rf', 'numerical', 'integerOnly'=>true),
			array('kilometraje', 'length', 'max'=>7),
			array('kilometraje', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nro_guia, id_vehiculo, id_rf, kilometraje, fecha, creado, modificado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'detallesOts' => array(self::HAS_MANY, 'DetallesOt', 'id_ot'),
			'idVehiculo' => array(self::BELONGS_TO, 'Vehiculos', 'id_vehiculo'),
			'idregistroFactura' => array(self::BELONGS_TO, 'RegistroFactura', 'id_rf'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'nro_guia' => Yii::t('app', 'Nro Guia'),
			'id_vehiculo' => null,
			'id_rf' => null,
			'kilometraje' => Yii::t('app', 'Kilometraje'),
			'fecha' => Yii::t('app', 'Fecha'),
			'creado' => Yii::t('app', 'Creado'),
			'modificado' => Yii::t('app', 'Modificado'),
			'detallesOts' => null,
			'idVehiculo' => null,
			'idregistroFactura' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nro_guia', $this->nro_guia);
		$criteria->compare('id_vehiculo', $this->id_vehiculo);
		$criteria->compare('id_rf', $this->id_rf);
		$criteria->compare('kilometraje', $this->kilometraje, true);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('creado', $this->creado, true);
		$criteria->compare('modificado', $this->modificado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        
        public function beforeValidate() {
            if ($this->isNewRecord)
                $this->creado = new CDbExpression('NOW()');

            $this->modificado = new CDbExpression('NOW()');

            return parent::beforeSave();
        }
}