<?php

/**
 * This is the model base class for the table "usuarios".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuarios".
 *
 * Columns in table "usuarios" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $usuario
 * @property string $contrasena
 * @property string $creado
 * @property string $modificado
 *
 */
abstract class BaseUsuarios extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuarios';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuarios|Usuarioses', $n);
	}

	public static function representingColumn() {
		return 'usuario';
	}

	public function rules() {
		return array(
			array('usuario, contrasena, creado, modificado', 'required'),
			array('usuario, contrasena', 'length', 'max'=>30),
			array('id, usuario, contrasena, creado, modificado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'usuario' => Yii::t('app', 'Usuario'),
			'contrasena' => Yii::t('app', 'Contrasena'),
			'creado' => Yii::t('app', 'Creado'),
			'modificado' => Yii::t('app', 'Modificado'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('usuario', $this->usuario, true);
		$criteria->compare('contrasena', $this->contrasena, true);
		$criteria->compare('creado', $this->creado, true);
		$criteria->compare('modificado', $this->modificado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}