<?php

/**
 * This is the model base class for the table "ivas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ivas".
 *
 * Columns in table "ivas" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $fecha
 * @property string $valor_iva
 *
 */
abstract class BaseIvas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ivas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Iva|Ivas', $n);
	}

	public static function representingColumn() {
		return 'valor_iva';
	}

	public function rules() {
		return array(
			array('fecha, valor_iva', 'required'),
			array('id', 'numerical', 'integerOnly'=>true),
			array('valor_iva', 'length', 'max'=>10),
			array('id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, fecha, valor_iva', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fecha' => Yii::t('app', 'Fecha'),
			'valor_iva' => Yii::t('app', 'Valor Iva'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('valor_iva', $this->valor_iva, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}